site_name: EggAI Multi-Agent Meta Framework
copyright: Copyright &copy; 2024 EggAI Technologies GmbH

theme:
  name: material
  features:
    - navigation.expand
  logo: assets/logo.png
  favicon: assets/favicon.png
  palette:
    primary: white

nav:
  - "Introduction": index.md
  - Concepts:
    - "Agent": concepts/agent.md
    - "Multi-Agent System": concepts/multi-agent-system.md
  - Examples:
    - "Getting Started": examples/getting_started.md
    - "Coordinator": examples/coordinator.md
    - "Websocket Gateway": examples/websocket_gateway.md
    - "LangChain Tool Calling": examples/langchain_tool_calling.md
    - "Shared Context": examples/shared-context.md
    - "LiteLLM Integration": examples/litellm_agent.md
    - "Multi-Agent Conversation": examples/multi_agent_conversation.md
    - "An Insurance Company Scenario": examples/ui_chat_with_agents.md
    - "Agent Evaluation & DSPy": examples/agent_evaluation_dspy.md
  - References:
    - "Agent": references/agent.md
    - "Channel": references/channel.md
    - "Message": references/message.md

plugins:
- include-markdown:
    comments: true
    start: <!--start-->
    end: <!--end-->
- mkdocstrings:
    handlers:
      python:
        paths: [sdk/eggai]

extra:
  generator: false